services:
  - type: web
    name: ikim-rms-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: JWT_SECRET
        generateValue: true
